/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson, AI assistant
-/
module

public import Mathlib.AlgebraicTopology.Quasicategory.StrictBicategory
public import Mathlib.CategoryTheory.Limits.Shapes.Pullback.HasPullback

/-!
# Fibration-stable pullback skeleton

This file gives a small model-side scaffold for the workshop project on fibration-stable strict
pullbacks and homotopy pullbacks of quasicategories. It does not try to interpret the general SCT
pullback fields. Instead, it names the narrower mathematical interfaces that can justify strict
simplicial-set pullbacks under explicit fibration hypotheses and can later feed a
homotopy-pullback adapter.

The intended first theorem is: if one leg of a cospan of quasicategories is an inner fibration,
then the strict simplicial-set pullback is again a quasicategory and models the homotopy pullback.
Natural-transformation comparisons in the surrounding SCT model are bicategorical 2-cells; this
file uses strict equality only for the special strict-pullback cone where the square commutes on the
nose.
-/

@[expose] public section

open CategoryTheory Simplicial Limits

namespace SCTFibrationPullbacksSkeleton

universe u

/-- Quasicategories are invariant under isomorphism of simplicial sets. -/
lemma quasicategoryOfIso {X Y : SSet.{u}} (e : X ≅ Y) [SSet.Quasicategory Y] :
    SSet.Quasicategory X where
  hornFilling' := by
    intro n i σ₀ h0 hn
    obtain ⟨σ, hσ⟩ := SSet.Quasicategory.hornFilling' (S := Y) (σ₀ ≫ e.hom) h0 hn
    use σ ≫ e.inv
    simpa [Category.assoc] using congrArg (fun f => f ≫ e.inv) hσ

/-- The morphism property generated by inner horn inclusions. -/
def innerHornInclusions : MorphismProperty SSet.{u} :=
  ⨆ n : ℕ,
    MorphismProperty.ofHoms
      (fun i : {i : Fin (n + 3) // 0 < i ∧ i < Fin.last (n + 2)} =>
        Λ[n + 2, i.1].ι)

/-- An inner fibration of simplicial sets: a map with the right lifting property against all inner
horn inclusions.

This local wrapper can later be replaced by a mathlib/infinity-cosmos name if one is added. The
workshop design question is how this relates to the book's `IsofibrationWitness` and to
model-category fibrations.
-/
abbrev InnerFibration {E B : SSet.{u}} (p : E ⟶ B) : Prop :=
  innerHornInclusions.rlp p

namespace StrictPullback

variable {C D E X : SSet.QCat.{u}} {F : C ⟶ E} {G : D ⟶ E}

/-- The strict simplicial-set pullback of a cospan of bundled quasicategories. -/
noncomputable abbrev obj (F : C ⟶ E) (G : D ⟶ E) : SSet.{u} :=
  pullback F.hom G.hom

/-- Strict pullbacks of quasicategories along a right inner fibration are quasicategories.

The intended proof takes an inner horn in `pullback F.hom G.hom`, projects it to horns in `C` and
`D`, fills the `C`-horn using the quasicategory structure on `C`, and then uses the inner-fibration
lifting property of `G` to fill the `D`-horn compatibly over `E`. The compatible pair of fillers is
exactly a filler in the strict pullback.
-/
lemma quasicategoryOfRightInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hG : InnerFibration G.hom) : SSet.Quasicategory (obj F G) := by
  sorry

/-- Strict pullbacks of quasicategories along a left inner fibration are quasicategories, by
symmetry from the right-leg version. -/
lemma quasicategoryOfLeftInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hF : InnerFibration F.hom) : SSet.Quasicategory (obj F G) := by
  haveI : SSet.Quasicategory (obj G F) := quasicategoryOfRightInnerFibration G F hF
  exact quasicategoryOfIso (pullbackSymmetry F.hom G.hom)

/-- Bundled strict pullback when the right leg is an inner fibration. -/
noncomputable def qcatOfRightInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hG : InnerFibration G.hom) : SSet.QCat.{u} :=
  ⟨obj F G, quasicategoryOfRightInnerFibration F G hG⟩

/-- Bundled strict pullback when the left leg is an inner fibration. -/
noncomputable def qcatOfLeftInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hF : InnerFibration F.hom) : SSet.QCat.{u} :=
  ⟨obj F G, quasicategoryOfLeftInnerFibration F G hF⟩

/-- First projection from a right-leg inner-fibration strict pullback. -/
noncomputable def pr1OfRightInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hG : InnerFibration G.hom) : qcatOfRightInnerFibration F G hG ⟶ C :=
  ObjectProperty.homMk (P := SSet.Quasicategory) (pullback.fst F.hom G.hom)

/-- Second projection from a right-leg inner-fibration strict pullback. -/
noncomputable def pr2OfRightInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hG : InnerFibration G.hom) : qcatOfRightInnerFibration F G hG ⟶ D :=
  ObjectProperty.homMk (P := SSet.Quasicategory) (pullback.snd F.hom G.hom)

/-- Strict commutativity of the right-leg inner-fibration pullback projections. -/
lemma commOfRightInnerFibration (F : C ⟶ E) (G : D ⟶ E) (hG : InnerFibration G.hom) :
    (pr1OfRightInnerFibration F G hG).hom ≫ F.hom =
      (pr2OfRightInnerFibration F G hG).hom ≫ G.hom :=
  pullback.condition

/-- Mediating map into the right-fibration strict pullback from a strictly commuting cone. -/
noncomputable def liftOfRightInnerFibration {F : C ⟶ E} {G : D ⟶ E}
    (hG : InnerFibration G.hom) (A : X ⟶ C) (B : X ⟶ D)
    (w : A.hom ≫ F.hom = B.hom ≫ G.hom) : X ⟶ qcatOfRightInnerFibration F G hG :=
  ObjectProperty.homMk (P := SSet.Quasicategory) (pullback.lift A.hom B.hom w)

/-- First strict β-rule for the right-leg inner-fibration strict pullback lift. -/
lemma lift_pr1_homOfRightInnerFibration {F : C ⟶ E} {G : D ⟶ E}
    (hG : InnerFibration G.hom) (A : X ⟶ C) (B : X ⟶ D)
    (w : A.hom ≫ F.hom = B.hom ≫ G.hom) :
    (liftOfRightInnerFibration hG A B w).hom ≫
      (pr1OfRightInnerFibration F G hG).hom = A.hom :=
  pullback.lift_fst A.hom B.hom w

/-- Second strict β-rule for the right-leg inner-fibration strict pullback lift. -/
lemma lift_pr2_homOfRightInnerFibration {F : C ⟶ E} {G : D ⟶ E}
    (hG : InnerFibration G.hom) (A : X ⟶ C) (B : X ⟶ D)
    (w : A.hom ≫ F.hom = B.hom ≫ G.hom) :
    (liftOfRightInnerFibration hG A B w).hom ≫
      (pr2OfRightInnerFibration F G hG).hom = B.hom :=
  pullback.lift_snd A.hom B.hom w

/-- Strict uniqueness for maps into the right-fibration strict pullback. -/
lemma hom_extOfRightInnerFibration {F : C ⟶ E} {G : D ⟶ E} {hG : InnerFibration G.hom}
    {H K : X ⟶ qcatOfRightInnerFibration F G hG}
    (h₁ : H.hom ≫ (pr1OfRightInnerFibration F G hG).hom =
      K.hom ≫ (pr1OfRightInnerFibration F G hG).hom)
    (h₂ : H.hom ≫ (pr2OfRightInnerFibration F G hG).hom =
      K.hom ≫ (pr2OfRightInnerFibration F G hG).hom) : H = K := by
  apply ObjectProperty.hom_ext
  exact pullback.hom_ext h₁ h₂

end StrictPullback

namespace HomotopyPullback

variable {C D E : SSet.QCat.{u}} {F : C ⟶ E} {G : D ⟶ E}

set_option backward.isDefEq.respectTransparency false in
/-- Bicategorical 2-cells between functors of quasicategories. -/
abbrev NatTrans (P E : SSet.QCat.{u}) (H K : P ⟶ E) : Type u :=
  H ⟶ K

set_option backward.isDefEq.respectTransparency false in
/-- Invertibility evidence for a bicategorical 2-cell. -/
abbrev TwoCellIsIso {P E : SSet.QCat.{u}} {H K : P ⟶ E}
    (α : NatTrans P E H K) : Type u :=
  ULift.{u} (PLift (IsIso α))

/-- Natural-isomorphism comparison between two functors of quasicategories. -/
abbrev NatIso (P E : SSet.QCat.{u}) (H K : P ⟶ E) : Type u :=
  (α : NatTrans P E H K) × TwoCellIsIso α

/-- Coherent comparison in a cone over a cospan.

This is the homotopy-pullback comparison datum between `pr1 ≫ F` and `pr2 ≫ G`.  A strict cone is
only a special case, converted by `strictConeComparison` below.
-/
abbrev ConeComparison {P C D E : SSet.QCat.{u}} (pr1 : P ⟶ C) (pr2 : P ⟶ D)
    (F : C ⟶ E) (G : D ⟶ E) : Type u :=
  NatIso P E (pr1 ≫ F) (pr2 ≫ G)

set_option backward.isDefEq.respectTransparency false in
/-- A strictly commuting cone gives coherent comparison data via the identity 2-cell transport. -/
noncomputable def strictConeComparison {P C D E : SSet.QCat.{u}} {pr1 : P ⟶ C}
    {pr2 : P ⟶ D} {F : C ⟶ E} {G : D ⟶ E} (h : pr1 ≫ F = pr2 ≫ G) :
    ConeComparison pr1 pr2 F G :=
  ⟨eqToHom h, ULift.up (PLift.up inferInstance)⟩

/-- The homotopy-pullback universal property in `Cat_∞`.

To make this definition correct, replace the placeholder by a structure expressing the
mapping-anima universal property. For every test quasicategory `X`, postcomposition with `pr1` and
`pr2`, together with the coherent comparison, should induce an equivalence
`Map(X,P) ≃ Map(X,C) ×^h_{Map(X,E)} Map(X,D)`, where the right-hand side is the
homotopy pullback of anima. Once `mapAnima`, coherent natural isomorphisms, and anima pullbacks are
available, those maps and equivalences should become explicit fields of this structure.
-/
def UniversalProperty {P : SSet.QCat.{u}} (pr1 : P ⟶ C) (pr2 : P ⟶ D)
    (comparison : ConeComparison pr1 pr2 F G) : Type (u + 1) := by
  sorry

/-- A homotopy-pullback candidate: cone data plus the `Cat_∞` universal property.

This structure is correct only when `universal` contains the mapping-anima universal property above.
The projection fields alone are not enough: a final SCT pullback package must prove that maps into
`obj` classify pairs of maps into `C` and `D` with coherent comparison over `E`.
-/
structure Candidate (F : C ⟶ E) (G : D ⟶ E) : Type (u + 1) where
  obj : SSet.QCat.{u}
  pr1 : obj ⟶ C
  pr2 : obj ⟶ D
  comparison : ConeComparison pr1 pr2 F G
  universal : UniversalProperty pr1 pr2 comparison

/-- Under an inner-fibration hypothesis, the strict pullback represents the homotopy pullback.

The projection fields are the ordinary strict pullback projections, and their strict commutativity
is converted to coherent comparison data. The main proof is the real homotopy-pullback theorem:
strict pullbacks along inner fibrations compute homotopy pullbacks in `Cat_∞`, equivalently satisfy
the mapping-anima universal property for every test quasicategory.
-/
noncomputable def representedByRightInnerFibration (F : C ⟶ E) (G : D ⟶ E)
    (hG : InnerFibration G.hom) : Candidate F G where
  obj := StrictPullback.qcatOfRightInnerFibration F G hG
  pr1 := StrictPullback.pr1OfRightInnerFibration F G hG
  pr2 := StrictPullback.pr2OfRightInnerFibration F G hG
  comparison := strictConeComparison (by
    apply ObjectProperty.hom_ext
    exact StrictPullback.commOfRightInnerFibration F G hG)
  universal := by
    sorry

end HomotopyPullback

/-
Important scope note: closing every `sorry` in this file would justify the fibration-specific case
where one leg of the cospan is an inner fibration.  That is enough for base-change and other
fibration-stable strict-pullback arguments.

It would not, by itself, fill the generated SCT model fields `pullbackCat`, `pullbackPr1`,
`pullbackPr2`, `pullbackComm`, `pullbackLift`, `pullbackBeta1`, `pullbackBeta2`, `pullbackUniq`,
and `pullbackEta` in `InternalMath/SCT/Model.lean`, because those fields are for arbitrary cospans
of synthetic categories.  The general fields still need a Reedy/homotopy-limit construction, or an
equivalent fibrant-replacement theorem for arbitrary cospans, plus adapters extracting the SCT cone,
lift, β, η, and uniqueness data from that construction.
-/

end SCTFibrationPullbacksSkeleton
