/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson
-/
module

public import InternalLean.Command

/-!
# InternalLean intro exercises

Open this file in your editor and read it from top to bottom. It introduces the usual
InternalLean workflow on a tiny type theory of nodes, primitive steps, and reachability.

How to use the exercises:

* The declarations named `exerciseXX_...` end in `sorry`. Replace each `sorry` with an internal
  proof term or internal tactic script.
* Hints are in `.lake/packages/InternalLean/Examples/IntroExercisesHints.lean`.
* Complete worked solutions are in
  `.lake/packages/InternalLean/Examples/IntroExercisesSolutions.lean`.

InternalLean declarations describe a type theory. The expressions after `internal def` are
internal terms/proofs checked by InternalLean, even though this file is a Lean file.

-/

@[expose] public section

/--
A toy type theory.

`Node` is the sort of nodes in the declared type theory. `Step x y` is a primitive edge, and
`Reach x y` is the reflexive/transitive closure generated by primitive steps.
-/
declare_type_theory IntroReach where
  /-- Internal node terms. -/
  syntax_sort Node

  /--
  Metadata for generic tools: `Node` is the main term sort of this type theory. The role does not
  add a rule or a model field; it tells diagnostics and future automation how to classify `Node`.
  -/
  syntax_sort_role Node : term_sort

  /-- Primitive one-step reachability. -/
  judgment Step (src : Node) (tgt : Node)

  /-- Derived reachability. -/
  judgment Reach (src : Node) (tgt : Node)

  /-- Three primitive nodes. -/
  lf_opaque start : Node
  lf_opaque mid : Node
  lf_opaque finish : Node

  /-- Primitive edge from `start` to `mid`. -/
  rule step_start_mid : Step start mid

  /-- Primitive edge from `mid` to `finish`. -/
  rule step_mid_finish : Step mid finish

  /-- Every node reaches itself. -/
  rule reach_refl (x : Node) : Reach x x

  /-- A primitive step gives a reachability proof. -/
  rule reach_of_step (src : Node) (tgt : Node) where
    premise edge : Step src tgt
    conclusion : Reach src tgt

  /-- Reachability is transitive. -/
  rule reach_trans (src : Node) (via : Node) (tgt : Node) where
    premise left : Reach src via
    premise right : Reach via tgt
    conclusion : Reach src tgt

  /-- A checked theorem can package a common proof in the theory itself. -/
  judgment_theorem reach_start_mid : Reach start mid :=
    reach_of_step start mid step_start_mid

#check_theory IntroReach

/-!
A model interface can be generated as soon as the theory exists. The solutions file transports
checked internal declarations over this interface.
-/

generate_model_interface IntroReach as IntroReachModel

generate_model_transport IntroReach reach_start_mid for IntroReachModel

namespace IntroReach

/-!
## Exercise 1: exact internal proof terms

Use the reflexivity rule to prove `Reach start start`.
-/

internal def exercise01_start_reaches_start : Reach start start := by
  sorry

/-!
## Exercise 2: using a rule with a premise

Turn the primitive edge `step_mid_finish` into a reachability proof.
-/

internal def exercise02_mid_reaches_finish : Reach mid finish := by
  sorry

/-!
## Exercise 3: composing proofs

Prove that `start` reaches `finish`. The middle node does not appear in the conclusion, so a tactic
with explicit arguments is the most predictable approach.
-/

internal def exercise03_start_reaches_finish : Reach start finish := by
  sorry

/-!
## Exercise 4: using internal parameters

The command `internal def` also supports binder-style declarations. Use the bound internal
parameter and apply reflexivity.
-/

internal def exercise04_refl_function (x : Node) : Reach x x := by
  sorry

/-!
## Exercise 5: local internal assumptions

`assumption` searches the internal context. Prove that an assumption can be returned unchanged.
-/

internal def exercise05_assumption (x : Node) (h : Reach x finish) : Reach x finish := by
  sorry

/-!
## Exercise 6: direct proof terms

Write the proof of `Reach start finish` in term mode. This form is useful when a proof is
small enough to read as a single internal term.
-/

internal def exercise06_direct_term : Reach start finish :=
  sorry

/-!
## Exercise 7: naming intermediate internal proofs

Use `have name : Type := proof` or `have name : Type := by ... end` blocks to name the two
subproofs before composing them. A tactic-mode `have` block needs the closing `end`; term-mode
`have` is useful for short proofs.
-/

internal def exercise07_have_blocks : Reach start finish := by
  sorry

/-!
## Exercise 8: internal functions with `intro`

A target such as `(x : Node) → Node` uses InternalLean's structural internal function type, even
though `IntroReach` did not declare a separate function former. In tactic mode, `intro x` opens
that internal function type by adding `x : Node` to the internal context and changing the goal to
the body type. Use it here to build a function from nodes to nodes.
-/

internal def exercise08_const_start_function : (x : Node) → Node := by
  sorry

/-!
## Exercise 9: changing across an internal definition

Internal definitions unfold during conversion. Define an alias for `finish`, then use `change` to
replace a goal mentioning the alias with the unfolded goal.
-/

internal def exercise09_last_node : Node := finish

internal def exercise09_change_alias : Reach exercise09_last_node exercise09_last_node := by
  sorry

/-!
## Exercise 10: abstracting a proof pattern

Turn transitivity itself into a reusable internal theorem with parameters and local proof
assumptions.
-/

internal def exercise10_compose_parameterized
    (src : Node) (via : Node) (tgt : Node)
    (left : Reach src via) (right : Reach via tgt) : Reach src tgt := by
  sorry

/-!
## Exercise 11: batched internal declarations

`internal_defs where` registers declarations in source order. Fill the first declaration with a
node and the second with a proof about that node.
-/

internal_defs where
  def exercise11_batch_node : Node := sorry
  def exercise11_batch_refl : Reach exercise11_batch_node exercise11_batch_node := sorry

/-!
Try uncommenting these commands after filling the exercises:
-/

-- #lint_type_theory_sorries IntroReach
-- #print_internal_registration_profile IntroReach


end IntroReach

/-!
## Transporting the exercise declarations

This command generates Lean methods over `IntroReachModel` from selected exercise declarations.
While an exercise still ends in `sorry`, the generated method is an admitted Lean declaration.
After you fill the exercise, rerunning elaboration replaces that admission with a checked replay
over the model.

For a single declaration, use `generate_model_transport IntroReach declaration for IntroReachModel`.
-/

generate_model_transports IntroReach only
  exercise02_mid_reaches_finish
  exercise03_start_reaches_finish
  exercise04_refl_function
  exercise06_direct_term
  exercise07_have_blocks
  exercise08_const_start_function
  exercise10_compose_parameterized
for IntroReachModel

-- `generate_model_transports IntroReach for IntroReachModel` transports everything

namespace IntroReachExercises

/-!
## A tiny Lean model

The generated model interface is an ordinary Lean structure. This model interprets every node as
`Unit`, and both judgments as `Unit`-valued predicates. It shows the shape of a model before you
replace the exercise admissions with checked proofs.
-/

/-- A small Lean model: every node is `Unit` and every judgment is `Unit`. -/
def unitModel : IntroReach.IntroReachModel where
  Node := Unit
  Step := fun _ _ => Unit
  Reach := fun _ _ => Unit
  start := ()
  mid := ()
  finish := ()
  step_start_mid := ()
  step_mid_finish := ()
  reach_refl := fun _ => ()
  reach_of_step := fun _ _ _ => ()
  reach_trans := fun _ _ _ _ _ => ()

#check IntroReach.IntroReachModel
#check IntroReach.IntroReachModel.reach_start_mid
#check IntroReach.IntroReachModel.exercise02_mid_reaches_finish
#check IntroReach.IntroReachModel.exercise03_start_reaches_finish
#check IntroReach.IntroReachModel.exercise04_refl_function
#check IntroReach.IntroReachModel.exercise06_direct_term
#check IntroReach.IntroReachModel.exercise07_have_blocks
#check IntroReach.IntroReachModel.exercise08_const_start_function
#check IntroReach.IntroReachModel.exercise10_compose_parameterized

example : unitModel.Reach unitModel.start unitModel.mid :=
  IntroReach.IntroReachModel.reach_start_mid unitModel

example : unitModel.Reach unitModel.start unitModel.finish :=
  IntroReach.IntroReachModel.exercise03_start_reaches_finish unitModel

example (x : unitModel.Node) : unitModel.Reach x x :=
  IntroReach.IntroReachModel.exercise04_refl_function unitModel x

example : unitModel.Reach unitModel.start unitModel.finish :=
  IntroReach.IntroReachModel.exercise06_direct_term unitModel

example : unitModel.Reach unitModel.start unitModel.finish :=
  IntroReach.IntroReachModel.exercise07_have_blocks unitModel

example : unitModel.Node :=
  IntroReach.IntroReachModel.exercise08_const_start_function unitModel unitModel.finish

example (x y z : unitModel.Node) (left : unitModel.Reach x y) (right : unitModel.Reach y z) :
    unitModel.Reach x z :=
  IntroReach.IntroReachModel.exercise10_compose_parameterized unitModel x y z left right

/-!
## Optional follow-ups

1. Add a fourth node and a new primitive step to `IntroReach`.
2. Add a theorem showing the new node is reachable from `start`.
3. Generate a model transport for that theorem.
4. Replace `unitModel` with a nontrivial Lean model, for example an inductive type of three nodes
   and propositions describing exactly the two primitive steps.
-/

end IntroReachExercises
