/-
Copyright (c) 2026 Dagur Asgeirsson. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dagur Asgeirsson, AI assistant
-/
module

public import InternalMath.HoTT.MLTT.Coproduct
public import InternalMath.HoTT.MLTT.Empty
public import InternalMath.HoTT.MLTT.Identity
public import InternalMath.HoTT.MLTT.Nat
public import InternalMath.HoTT.MLTT.Pi
public import InternalMath.HoTT.MLTT.Sigma
public import InternalMath.HoTT.MLTT.Unit

/-!
# Martin-Löf type theory, HoTT book Appendix A.2

This module assembles the reusable MLTT layers from `InternalMath.HoTT.MLTT.*` and adds a
Tarski-style universe-code layer.  The base layer `MLTT.Basic` contains the three syntax families
`Ctx`, `Ty`, and `Tm`, together with the four basic judgments `IsCtx`, `IsTy`, `IsTm`, and `EqTm`.

The intended design is a diamond-shaped collection of independent mixin theories over shared
prerequisites such as `MLTT.Basic` and `MLTT.Substitution`, with full MLTT extending all selected
mixins.  InternalLean currently flattens shared ancestry without deduplication, so the implemented
hierarchy is temporarily linear:

`MLTT.Basic → MLTT.Substitution → MLTT.Pi → MLTT.Sigma → MLTT.Coproduct → MLTT.Empty →
 MLTT.Unit → MLTT.Nat → MLTT.Identity → MLTT`.

The plan for true mixin composition is recorded in
`../InternalLean/Plans/InternalLeanTheoryMixinCompositionSpec.md`.
-/

@[expose] public section

/-- Full MLTT assembled from the reusable layers, plus Tarski-style universe syntax. -/
declare_type_theory MLTT extends MLTT.Coproduct, MLTT.Empty, MLTT.Identity, MLTT.Nat, MLTT.Pi,
    MLTT.Sigma, MLTT.Unit where

  model_section Universes

  /-- Universe indices, generated by `levelZero` and `levelSucc`. -/
  syntax_sort UnivLevel

  lf_opaque levelZero : UnivLevel
  lf_opaque levelSucc (i : UnivLevel) : UnivLevel

  /-- Universe type `𝒰ᵢ` in a context. -/
  lf_opaque univ (Γ : Ctx) (i : UnivLevel) : Ty Γ

  /-- Decode a universe element/code as an ordinary type. -/
  lf_opaque elTy (Γ : Ctx) (i : UnivLevel) (A : Tm Γ) : Ty Γ

  rule univ_form {Γ : Ctx} (i : UnivLevel) where
    premise ctx : IsCtx Γ
    conclusion : IsTy (univ Γ i)

  rule el_form {Γ : Ctx} (i : UnivLevel) (A : Tm Γ) where
    premise code : IsTm A (univ Γ i)
    conclusion : IsTy (elTy Γ i A)
